import Button from 'components/common/Button'
import Head from 'next/head'
import Navbar from '../components/common/Navbar'
import Hero from '../components/Home/Hero'
import Section from 'components/Home/Section'
import Footer from 'components/common/Footer'
import Services from 'components/Home/Services'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link href='http://fonts.cdnfonts.com/css/satoshi' rel='stylesheet' />
			</Head>

			<div>
				<Navbar />
			</div>
			<Hero />

			<Section h2={'About us'} link={'/images/aboutus.png'} />

			<Services />
			<Section h2={'What we do'} link={'/images/whatwedo.png'} />
			<Footer />
		</>
	)
}
